---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chaostoolkit-experiments
data:
  health-instances.yaml: |
    version: 1.0.0
    title: What happens if we terminate an instance?
    description: Everything should continue working as if nothing happened
    tags:
    - k8s
    - pod
    - deployment
    steady-state-hypothesis:
      title: The app is healthy
      probes:
      - name: all-apps-are-healthy
        type: probe
        tolerance: true
        provider:
          type: python
          func: all_microservices_healthy
          module: chaosk8s.probes
          arguments:
            ns: go-demo-8
    method:
    - type: action
      name: terminate-app-pod
      provider:
        type: python
        module: chaosk8s.pod.actions
        func: terminate_pods
        arguments:
          rand: true
          ns: go-demo-8
      pauses: 
        after: 10
  node.yaml: |
    version: 1.0.0
    title: What happens if we drain a node
    description: All the instances are distributed among healthy nodes and the applications are healthy
    tags:
    - k8s
    - node
    method:
    - type: action
      name: drain-node
      provider:
        type: python
        func: drain_nodes
        module: chaosk8s.node.actions
        arguments:
          label_selector: beta.kubernetes.io/os=linux
          count: 1
          delete_pods_with_local_storage: true
      pauses: 
        after: 180
    rollbacks:
    - type: action
      name: uncordon-node
      provider:
        type: python
        func: uncordon_node
        module: chaosk8s.node.actions
        arguments:
          label_selector: beta.kubernetes.io/os=linux
